export const TYPE_LOAD_START = 'LOAD_START'
export const TYPE_LOAD_FINISH = 'LOAD_FINISH'
export const TYPE_LOAD_ERROR = 'LOAD_ERROR'
export const STATUS_LOADING = 'loading'
export const STATUS_ERROR = 'error'
export const STATUS_FINISH = 'finish'
export const TYPE_GOTO_FULL_SCREEN = 'goto_full_screen'
export const TYPE_LEAVE_FULL_SCREEN = 'leave_full_screen'
export const STATUS_FULL_SCREEN = 'full_screen'
export const STATUS_NOT_FULL_SCREEN = 'not_full_screen'

// import {TYPE_LOAD_START,TYPE_LOAD_FINISH,TYPE_LOAD_ERROR,STATUS_LOADING,STATUS_ERROR,STATUS_FINISH} from './../constants/constants.js'
